In [1]:
import h5py as hp
import pandas as pd
import numpy as np
import time as tm

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

In [2]:
size=0
columns=['msno','song_id','song_length','played_length','day','artist_id','hear_percent','hear_gap']
dataset2=pd.DataFrame(columns=columns)
for ii in range(97,101,1):
    for j in range(97,123,1):
        file_name='a'+chr(ii)+chr(j)+'.h5'
        df=pd.read_hdf(file_name,'a')
        df['hear_gap']=df.hear_percent.apply(lambda a:0 if a ==0 else 1 if a<=0.5 else 2 if (a>0.5) & (a<=1) else 3 )
        dataset2=dataset2.add(df[df['hear_percent']==0],fill_value=0)
        df.to_hdf(file_name,'a')
        print ('File_name:%s Data_size:%d'%(file_name,len(df)))
        size=size+len(df)
        if(ii==100 and j==108):
            break
print ('Data_size:%d'%(size))

File_name:aaa.h5 Data_size:9221234
File_name:aab.h5 Data_size:8881714
File_name:aac.h5 Data_size:8771945
File_name:aad.h5 Data_size:8569205
File_name:aae.h5 Data_size:7698014
File_name:aaf.h5 Data_size:7753748
File_name:aag.h5 Data_size:8022754
File_name:aah.h5 Data_size:7379201
File_name:aai.h5 Data_size:7766798
File_name:aaj.h5 Data_size:7840978
File_name:aak.h5 Data_size:7739387
File_name:aal.h5 Data_size:7768542
File_name:aam.h5 Data_size:8235947
File_name:aan.h5 Data_size:8410246
File_name:aao.h5 Data_size:8988572
File_name:aap.h5 Data_size:9389537
File_name:aaq.h5 Data_size:9336586
File_name:aar.h5 Data_size:9310190
File_name:aas.h5 Data_size:9289376
File_name:aat.h5 Data_size:9328716
File_name:aau.h5 Data_size:9354860
File_name:aav.h5 Data_size:9311343
File_name:aaw.h5 Data_size:9273923
File_name:aax.h5 Data_size:9305030
File_name:aay.h5 Data_size:9328121
File_name:aaz.h5 Data_size:9289821
File_name:aba.h5 Data_size:9323302
File_name:abb.h5 Data_size:9339267
File_name:abc.h5 Data_size:9225520
File_name:abd.h5 Data_size:9302418
File_name:abe.h5 Data_size:9286359
File_name:abf.h5 Data_size:9174488
File_name:abg.h5 Data_size:9178719
File_name:abh.h5 Data_size:9252550
File_name:abi.h5 Data_size:9272507
File_name:abj.h5 Data_size:9312125
File_name:abk.h5 Data_size:9239103
File_name:abl.h5 Data_size:9204435
File_name:abm.h5 Data_size:9208042
File_name:abn.h5 Data_size:9304466
File_name:abo.h5 Data_size:9344792
File_name:abp.h5 Data_size:9330570
File_name:abq.h5 Data_size:9355005
File_name:abr.h5 Data_size:9341171
File_name:abs.h5 Data_size:9381414
File_name:abt.h5 Data_size:9374803
File_name:abu.h5 Data_size:9369473
File_name:abv.h5 Data_size:9364580
File_name:abw.h5 Data_size:9163010
File_name:abx.h5 Data_size:9109776
File_name:aby.h5 Data_size:9042450
File_name:abz.h5 Data_size:9160649
File_name:aca.h5 Data_size:9143326
File_name:acb.h5 Data_size:9332170
File_name:acc.h5 Data_size:9360130
File_name:acd.h5 Data_size:9129983
File_name:ace.h5 Data_size:9019562
File_name:acf.h5 Data_size:9071522
File_name:acg.h5 Data_size:8864148
File_name:ach.h5 Data_size:9030730
File_name:aci.h5 Data_size:8943708
File_name:acj.h5 Data_size:9293259
File_name:ack.h5 Data_size:9287989
File_name:acl.h5 Data_size:9176238
File_name:acm.h5 Data_size:9192555
File_name:acn.h5 Data_size:9340950
File_name:aco.h5 Data_size:8875536
File_name:acp.h5 Data_size:8542962
File_name:acq.h5 Data_size:8420741
File_name:acr.h5 Data_size:8922434
File_name:acs.h5 Data_size:9081829
File_name:act.h5 Data_size:9025964
File_name:acu.h5 Data_size:9196962
File_name:acv.h5 Data_size:9438892
File_name:acw.h5 Data_size:9347696
File_name:acx.h5 Data_size:9257079
File_name:acy.h5 Data_size:9341904
File_name:acz.h5 Data_size:9290002
File_name:ada.h5 Data_size:9219636
File_name:adb.h5 Data_size:9105945
File_name:adc.h5 Data_size:8331209
File_name:add.h5 Data_size:8814203
File_name:ade.h5 Data_size:9420367
File_name:adf.h5 Data_size:9393308
File_name:adg.h5 Data_size:9209976
File_name:adh.h5 Data_size:9238527
File_name:adi.h5 Data_size:9407007
File_name:adj.h5 Data_size:9388424
File_name:adk.h5 Data_size:9374272
File_name:adl.h5 Data_size:7205858
Data_size:811563785

In [3]:
df.head()

,msno,song_id,song_length,played_length,day,artist_id,hear_percent,hear_gap
0,5471836,159134550,236121,236121,11,5603802,1.000000,2
1,12628193,143715991,298945,4010,12,3051448,0.013414,1
2,66768647,171890544,215197,189231,10,4261,0.879338,2
3,338067507366,5975275,178625,178625,12,55135,1.000000,2
4,127131638,174913074,249443,249443,12,1357924,1.000000,2

In [4]:
dataset2.head()

,msno,song_id,song_length,played_length,day,artist_id,hear_percent,hear_gap
0,2.9342e+07,1.12806e+08,230000,0,27,197917,0,0
9,1.39102e+08,2.13904e+07,343000,0,30,54536,0,0
10,1.94932e+06,3.22415e+07,228000,0,9,1.51502e+06,0,0
15,2.89823e+07,2.23108e+08,496803,0,39,2.27502e+06,0,0
16,2.20823e+07,2.00518e+06,227579,0,20,3930,0,0

In [6]:
#dataset2.to_hdf('hear_percent_zero.h5','a')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:1471: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->floating,key->block0_values] [items->['msno', 'song_id', 'song_length', 'played_length', 'day', 'artist_id', 'hear_percent', 'hear_gap']]

  return pytables.to_hdf(path_or_buf, key, self, **kwargs)

In [7]:
dataset2

,msno,song_id,song_length,played_length,day,artist_id,hear_percent,hear_gap
0,2.9342e+07,1.12806e+08,230000,0,27,197917,0,0
9,1.39102e+08,2.13904e+07,343000,0,30,54536,0,0
10,1.94932e+06,3.22415e+07,228000,0,9,1.51502e+06,0,0
15,2.89823e+07,2.23108e+08,496803,0,39,2.27502e+06,0,0
16,2.20823e+07,2.00518e+06,227579,0,20,3930,0,0
18,6.93995e+07,1.63635e+08,181000,0,30,2.29886e+06,0,0
22,4.70028e+06,2.14019e+08,231000,0,6,663822,0,0
23,3.38067e+11,1.51076e+08,206007,0,30,3.10764e+06,0,0
27,1.8727e+06,5.04304e+06,216163,0,16,9480,0,0
31,7.20827e+07,2.87888e+06,272000,0,27,40080,0,0
33,3.38191e+11,1.35948e+08,546337,0,25,4.06021e+06,0,0
35,1.40525e+08,9.52287e+06,324000,0,5,28134,0,0
37,3.38133e+11,1.74859e+08,470000,0,17,5.93821e+06,0,0
40,2.86587e+07,1.96008e+08,219000,0,30,52634,0,0
44,5.40782e+06,1.03999e+08,233680,0,1,11725,0,0
45,1.03301e+08,3.74185e+06,269000,0,8,55718,0,0
46,4.35704e+07,1.02454e+06,225020,0,2,3083,0,0
51,3.3817e+11,1.73517e+08,705000,0,48,1.47102e+06,0,0
52,1.20741e+08,1.67995e+08,270000,0,2,30305,0,0
55,6.84341e+07,7.19403e+06,286000,0,5,208141,0,0
56,3.38135e+11,2.58042e+06,498474,0,48,4715,0,0
57,1.07245e+08,2.12157e+08,185000,0,13,5301,0,0
58,1.94204e+08,4.51449e+06,603000,0,45,188061,0,0
59,9.68733e+07,1.784e+08,244000,0,5,747138,0,0
60,1.07294e+08,4.01998e+06,231000,0,29,10939,0,0
61,1.46709e+08,8.82032e+07,353000,0,56,491534,0,0
64,1.44011e+08,1.58435e+06,208000,0,16,29326,0,0
65,7.55885e+06,2.05518e+08,208000,0,30,4.33097e+06,0,0
67,2.1494e+06,2.04475e+08,212000,0,11,2.57522e+06,0,0
68,6.32696e+07,1.36544e+06,298632,0,4,21339,0,0
...,...,...,...,...,...,...,...,...
9841445,3.38067e+11,1.97902e+08,216196,0,29,10939,0,0
9841781,5.29874e+07,1.40493e+06,252186,0,29,5306,0,0
9841806,3.21039e+07,883974,270000,0,29,2002,0,0
9842089,1.09428e+07,1.99153e+08,234000,0,23,6065,0,0
9842300,3.76986e+07,4.60785e+07,279000,0,29,2.55167e+06,0,0
9842510,1.29916e+08,6.09253e+07,219000,0,27,850466,0,0
9842941,3.3807e+11,2.02079e+06,134000,0,29,35714,0,0
9843018,4.71157e+07,5.16946e+07,295149,0,29,1.03448e+06,0,0
9843141,3.38064e+11,1.96473e+08,264079,0,28,6.63976e+06,0,0
9843294,5.2587e+07,1.92477e+08,236000,0,29,2.29581e+06,0,0
9843514,3.38064e+11,2.30675e+06,185000,0,29,335,0,0
9843571,3.3807e+11,1.94178e+08,210000,0,29,926914,0,0
9843974,3.75055e+07,4.13486e+06,291000,0,29,7332,0,0
9844637,3.38067e+11,1.81346e+06,292000,0,29,39190,0,0
9844889,1.1384e+08,1.39454e+06,258097,0,29,13627,0,0
9845107,5.30366e+07,1.79968e+08,237218,0,29,2.42453e+06,0,0
9845236,1.3925e+08,1.76864e+08,296000,0,29,2.39714e+06,0,0
9845262,3.3807e+11,1.94601e+08,296516,0,26,187255,0,0
9845420,1.42808e+08,3.64752e+06,580000,0,29,195386,0,0
9845679,9.82026e+07,897199,268000,0,29,630,0,0
9845922,3.38064e+11,1.35588e+06,268000,0,29,21982,0,0
9846057,3.38064e+11,3.70933e+06,244000,0,29,54794,0,0
9846094,2.80811e+07,1.91686e+06,208000,0,29,3137,0,0
9846629,3.06669e+07,5.70533e+07,264173,0,29,9510,0,0
9846914,3.38065e+11,5.66186e+07,263131,0,29,3.09277e+06,0,0
9846976,1.34569e+08,1.70592e+06,262000,0,29,12866,0,0
9847014,1.3512e+08,1.08987e+08,213000,0,29,48967,0,0
9847030,4.31314e+07,2.08593e+08,252000,0,29,51937,0,0
9847199,3.38063e+11,1.86196e+08,237000,0,29,40080,0,0
9847299,1.25529e+08,1.96008e+08,221000,0,29,52634,0,0

In [9]:
dataset2.groupby('artist_id').count().reset_index().sort_values('msno',ascending=False)

,artist_id,msno,song_id,song_length,played_length,day,hear_percent,hear_gap
2507,4261.0,100546,100546,100546,100546,100546,100546,100546
4238,6651.0,71119,71119,71119,71119,71119,71119,71119
5431,8280.0,44975,44975,44975,44975,44975,44975,44975
3203,5301.0,42961,42961,42961,42961,42961,42961,42961
35054,49897.0,37052,37052,37052,37052,37052,37052,37052
30892,43934.0,35738,35738,35738,35738,35738,35738,35738
192666,2993763.0,34808,34808,34808,34808,34808,34808,34808
9,14.0,29988,29988,29988,29988,29988,29988,29988
28417,40080.0,28443,28443,28443,28443,28443,28443,28443
37078,52634.0,26237,26237,26237,26237,26237,26237,26237
176018,2578468.0,25810,25810,25810,25810,25810,25810,25810
32101,45702.0,25497,25497,25497,25497,25497,25497,25497
9587,13667.0,19287,19287,19287,19287,19287,19287,19287
7438,10939.0,18976,18976,18976,18976,18976,18976,18976
50,74.0,18880,18880,18880,18880,18880,18880,18880
168366,2424531.0,18743,18743,18743,18743,18743,18743,18743
110583,747138.0,18646,18646,18646,18646,18646,18646,18646
140001,1357924.0,18588,18588,18588,18588,18588,18588,18588
8858,12749.0,18075,18075,18075,18075,18075,18075,18075
231176,4330967.0,16033,16033,16033,16033,16033,16033,16033
21605,30305.0,15926,15926,15926,15926,15926,15926,15926
15275,21493.0,14826,14826,14826,14826,14826,14826,14826
17659,24877.0,14704,14704,14704,14704,14704,14704,14704
125491,1034484.0,14390,14390,14390,14390,14390,14390,14390
28835,40703.0,14313,14313,14313,14313,14313,14313,14313
18153,25638.0,14084,14084,14084,14084,14084,14084,14084
38512,54536.0,13672,13672,13672,13672,13672,13672,13672
5029,7713.0,13657,13657,13657,13657,13657,13657,13657
183007,2750938.0,13438,13438,13438,13438,13438,13438,13438
157874,2246889.0,13216,13216,13216,13216,13216,13216,13216
...,...,...,...,...,...,...,...,...
134663,1214030.0,1,1,1,1,1,1,1
134660,1214016.0,1,1,1,1,1,1,1
134624,1213494.0,1,1,1,1,1,1,1
134659,1213999.0,1,1,1,1,1,1,1
134625,1213504.0,1,1,1,1,1,1,1
134626,1213536.0,1,1,1,1,1,1,1
134627,1213537.0,1,1,1,1,1,1,1
134629,1213540.0,1,1,1,1,1,1,1
134630,1213541.0,1,1,1,1,1,1,1
134631,1213570.0,1,1,1,1,1,1,1
134632,1213587.0,1,1,1,1,1,1,1
134633,1213591.0,1,1,1,1,1,1,1
134634,1213609.0,1,1,1,1,1,1,1
134636,1213640.0,1,1,1,1,1,1,1
134637,1213654.0,1,1,1,1,1,1,1
134639,1213669.0,1,1,1,1,1,1,1
134641,1213673.0,1,1,1,1,1,1,1
134642,1213707.0,1,1,1,1,1,1,1
134643,1213742.0,1,1,1,1,1,1,1
134644,1213743.0,1,1,1,1,1,1,1
134645,1213758.0,1,1,1,1,1,1,1
134646,1213778.0,1,1,1,1,1,1,1
134651,1213873.0,1,1,1,1,1,1,1
134652,1213878.0,1,1,1,1,1,1,1
134654,1213899.0,1,1,1,1,1,1,1
134655,1213913.0,1,1,1,1,1,1,1
134656,1213938.0,1,1,1,1,1,1,1
134657,1213943.0,1,1,1,1,1,1,1
134658,1213946.0,1,1,1,1,1,1,1
305567,21392081.0,1,1,1,1,1,1,1